server:
  port: 8166
  servlet:
    context-path: /web-market-carts
utils:
  cart:
    prefix: SPRING_WEB_APP_
integrations:
  core-service:
    url: http://localhost:5555/core
    timeout:
      connect: 2000
      read: 10000
      write: 2000
